### ISSUE TITLE
Support for Safari on macOS

### ISSUE THREAD

**Issue by zmilonas** [osnr/TabFS#6]
In the latest Safari 14 for macOS there is support for the standard WebExtensions API - https://developer.apple.com/documentation/safariservices/safari_web_extensions 

Maybe it would be possible without much changes to support Safari as well? 
For the publishing side it might be a little more complicated since it requires Mac App Store publication but it might be feasible.

**Comment by osnr** [comment]
Yeah, I think it's totally possible and might be quite easy to do the port; I just haven't looked into it 😅 
I might at some point -- or if someone else wants to try, go ahead; I'll certainly accept a pull request for it.

As with Firefox, we would probably need a way for people to compile it on their end and permanently load it as an unsigned extension (and have decent instructions for that, maybe modify the Makefile or install.sh). I'm not that interested in publishing this as a signed binary; I think that would set unfortunate expectations for reliability and security that we're not prepared to meet, and it would discourage [extension-side experiments](https://twitter.com/rsnous/status/1345113873792126976).

**Comment by jtagcat** [comment]
Somewhat related, if somebody wants to seriously look in to it: #28

**Comment by osnr** [comment]
Think I just got this working!

See #64 -- I would love it if someone tried this out and reported back about whether it builds and works on their machine, because the build and install process uses more Mac and Xcode stuff that I don't trust as much as the normal Unix stuff.

It won't persist across Safari restarts, because it's currently an unsigned extension; will have to think more about that.

I may write more about the architecture of the Safari port in the sponsor newsletter this week; it's more complicated than I'd like. Mac app -> WebExtension code (i.e. background.js that is the same as on Chrome) + Safari native extension code -> XPC service -> TabFS server subprocess -> tabfs.c subprocess
