### ISSUE TITLE
How to get the execute-script results?

### ISSUE THREAD

**Issue by jet10000** [osnr/TabFS#63]
Hi,

```
echo 'console.log(document.getElementById("currHeight").textContent)' > mnt/tabs/last-focused/execute-script
```

How to get the `currHeight` return's value?

**Comment by osnr** [comment]
I think you could `tail -f` (or otherwise keep open) `console` before you run the script: https://github.com/osnr/TabFS/blob/d7f462e96415fcbb265cdaac854ddfc47b3482ca/test/test.c#L90 and then when your script logs, it would come out through `console`. Let me know if that doesn't work.

I don't love this interface, so other ideas are welcome (we could make a synthetic executable in the folder that you could run w/ argument, for instance)
